// Generated by CoffeeScript 1.6.3
var badString, endsWith, okString, removeTopFolder, stripFolder, tailAfterFirst, tailAfterLast;

okString = function(str) {
  return (str != null) && str.length > 0;
};

badString = function(str) {
  return !(okString(str));
};

tailAfterLast = function(str, char) {
  var i;
  i = str.lastIndexOf(char);
  if (i > 0) {
    return str.slice(i + 1);
  } else {
    return "";
  }
};

tailAfterFirst = function(str, char) {
  var i;
  i = str.indexOf(char);
  if (i > 0) {
    return str.slice(i + 1);
  } else {
    return "";
  }
};

endsWith = function(str, suffix) {
  return str.indexOf(suffix, str.length - suffix.length) !== -1;
};

stripFolder = function(path) {
  return tailAfterLast(path, '/');
};

removeTopFolder = function(fileName) {
  return tailAfterFirst(fileName, '/');
};

if (typeof exports !== "undefined" && exports !== null) {
  exports.okString = okString;
  exports.badString = badString;
  exports.tailAfterLast = tailAfterLast;
  exports.tailAfterFirst = tailAfterFirst;
  exports.removeTopFolder = removeTopFolder;
  exports.stripFolder = stripFolder;
  exports.endsWith = endsWith;
}
